
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.juangio31.notebooks.analyze;

/** CUP generated class containing symbol constants. */
public class CParserSym {
  /* terminals */
  public static final int DIGITO = 4;
  public static final int POTENCIA = 11;
  public static final int TEXTO = 3;
  public static final int SUMA = 7;
  public static final int UMENOS = 16;
  public static final int MULT = 9;
  public static final int EOF = 0;
  public static final int FINLINEA = 15;
  public static final int FORMAT = 6;
  public static final int DIV = 10;
  public static final int ID = 2;
  public static final int IGUAL = 14;
  public static final int PAR_I = 12;
  public static final int error = 1;
  public static final int PRINT = 5;
  public static final int RESTA = 8;
  public static final int PAR_D = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "TEXTO",
  "DIGITO",
  "PRINT",
  "FORMAT",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "POTENCIA",
  "PAR_I",
  "PAR_D",
  "IGUAL",
  "FINLINEA",
  "UMENOS"
  };
}

