
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.juangio31.notebooks.analyze;

/** CUP generated class containing symbol constants. */
public class MParserSym {
  /* terminals */
  public static final int CADENA = 10;
  public static final int HEADER_1 = 2;
  public static final int HASH = 11;
  public static final int ITALIC = 13;
  public static final int PLUS = 8;
  public static final int EOF = 0;
  public static final int BOLD = 14;
  public static final int error = 1;
  public static final int SPACE = 12;
  public static final int INCISO = 9;
  public static final int BOLD_ITALIC = 15;
  public static final int HEADER_6 = 7;
  public static final int HEADER_5 = 6;
  public static final int HEADER_4 = 5;
  public static final int HEADER_3 = 4;
  public static final int HEADER_2 = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HEADER_1",
  "HEADER_2",
  "HEADER_3",
  "HEADER_4",
  "HEADER_5",
  "HEADER_6",
  "PLUS",
  "INCISO",
  "CADENA",
  "HASH",
  "SPACE",
  "ITALIC",
  "BOLD",
  "BOLD_ITALIC"
  };
}

