
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.juangio31.notebooks.analyzers;

/** CUP generated class containing symbol constants. */
public class MParserSym {
  /* terminals */
  public static final int HEADER2 = 9;
  public static final int HEADER1 = 8;
  public static final int LIST_ITEM_NUM = 5;
  public static final int ITALIC = 3;
  public static final int EOF = 0;
  public static final int BOLD = 2;
  public static final int error = 1;
  public static final int BOLD_ITALIC = 4;
  public static final int TEXT = 6;
  public static final int HEADER6 = 13;
  public static final int HEADER5 = 12;
  public static final int HEADER4 = 11;
  public static final int ENDL = 15;
  public static final int HD = 14;
  public static final int HEADER3 = 10;
  public static final int LIST_ITEM_HYPHEN = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOLD",
  "ITALIC",
  "BOLD_ITALIC",
  "LIST_ITEM_NUM",
  "TEXT",
  "LIST_ITEM_HYPHEN",
  "HEADER1",
  "HEADER2",
  "HEADER3",
  "HEADER4",
  "HEADER5",
  "HEADER6",
  "HD",
  "ENDL"
  };
}

